### ISSUE TITLE
Volunteer to do some wiki work

### ISSUE THREAD

**Issue by sealchan1** [Shadows-of-Fire/Plants#118]
Send me a full list of plants available in 1.12 and I will gradually create pages for those plants that do not have articles and that are in keeping with the content of those pages which do exist.

I'm enjoying the work of finding and collecting the plants provided by your mod in my modded MInecraft survival game.

**Comment by Shadows-of-Fire** [comment]
I am planning to deprecate the wiki in favor of ingame documentation in 1.14, so this should not be necessary.  If you still wish to proceed anyway (Since the wiki is open) the list of plants is available in this class: https://github.com/Shadows-of-Fire/Plants/blob/master/src/main/java/shadows/plants2/data/enums/TheBigBookOfEnums.java

Unfortunately some of the older plants do not use their english name as their constant declaration, they use their genus followed by the first letter of their species (which isn't a super useful identifier).

However, those plants which use unusual names have their fully translated name available in https://github.com/Shadows-of-Fire/Plants/blob/master/src/main/resources/assets/plants2/lang/en_us.lang
